### ISSUE TITLE
Default album art shows as a grey image

### ISSUE THREAD

**Issue by the-r0cket06** [leinelissen/jellyfin-audio-player#8]
I have some albums that don't have unique album art yet due to matching issues and are utilizing a default band image. In the app these appear as grey boxes instead of the default band album art that is visible on the website.

**Comment by leinelissen** [comment]
Wow, that's a great edge case 😅. Let me check out the API responses and see if there is a way to make that work in this app as well.

**Comment by the-r0cket06** [comment]
Had a chance to look at the logs while opening one of these albums and get the following error message.

[2020-08-27 23:10:58.529 -03:00] [ERR] Error processing request. URL: "http://domain/Items/3a07d91b6e0cf28f614b8771b53bfdd8/Images/Primary?format=jpeg"
MediaBrowser.Common.Extensions.ResourceNotFoundException: The River CDS does not have an image of type Primary
   at MediaBrowser.Api.Images.ImageService.GetImage(ImageRequest request, Guid itemId, BaseItem item, Boolean isHeadRequest)
   at Emby.Server.Implementations.Services.ServiceExecGeneral.Execute(Type serviceType, IRequest request, Object instance, Object requestDto, String requestName)
   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost httpHost, Object requestDto, IRequest req)
   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IRequest httpReq, HttpResponse httpRes, ILogger logger, CancellationToken cancellationToken)
   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IHttpRequest httpReq, String urlString, String host, String localPath, CancellationToken cancellationToken)

**Comment by leinelissen** [comment]
Right, that makes sense, as it tries to load up the image for the particular track, and/or album I guess. Thanks for the help!

**Comment by leinelissen** [comment]
Hey there! I've looked in to the issues but it seems a bit hard to solve. First off, Jellyfin doesn't really support inheritance for images on the server side (this is what the error you posted is about). While I could do a check if the image is there, I would need to do twice or triple the amount of requests in order to retrieve all images. On top of that, the web client for Jellyfin also doesn't seem to fall back to an artist's image if a track or album is missing it. 

I am closing this issue for now, but maybe if the back-end has a better way to fall back to these types of images, it can be considered for this application as well. If I've missed anything important, do let me know as well.

Cheers!
